In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/IS110_BPerformance_Bucago/IS110_repo_Bucago

/content/drive/MyDrive/IS110_BPerformance_Bucago/IS110_repo_Bucago


In [3]:
!pwd

/content/drive/MyDrive/IS110_BPerformance_Bucago/IS110_repo_Bucago


# **EXERCISE A**

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

In [4]:
import numpy as np

In [5]:
A = np.array([[10, 20, 30], [40, 50, 60]])

In [6]:
print("Shape of A:", A.shape)

Shape of A: (2, 3)


In [7]:
print("Max value using method:", A.max())

Max value using method: 60


In [8]:
print("Max value using np function:", np.max(A))

Max value using np function: 60


# **EXERCISE B**



B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.


In [9]:
B = np.ones((5, 5), dtype=int)

In [10]:
print(B)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
print("Shape:", B.shape)

Shape: (5, 5)


In [12]:
print("Size:", B.size)

Size: 25


In [13]:
print("Dimensions:", B.ndim)

Dimensions: 2


# **EXERCISE C**

In [14]:
C = np.arange(-5, 6)

In [15]:
result = C * 2

In [16]:
print("Original Array:", C)

Original Array: [-5 -4 -3 -2 -1  0  1  2  3  4  5]


In [17]:
print("Resulting Array:", result)

Resulting Array: [-10  -8  -6  -4  -2   0   2   4   6   8  10]


# **PUSH IN PYTHONENVI**

In [18]:
!find /content/drive/MyDrive/ -name "Chapter5_NumPyExercise.ipynb"

/content/drive/MyDrive/Colab Notebooks/Chapter5_NumPyExercise.ipynb
/content/drive/MyDrive/IS110_BPerformance_Bucago/IS110_repo_Bucago/PythonEnvi_Bucago/Chapter5_NumPyExercise.ipynb


In [ ]:
!git config --global user.email "princesskyle.bucago@students.isatu.edu.ph"
!git config --global user.name "Juami Shaniqua Desio"

In [19]:
!cp "/content/drive/MyDrive/Colab Notebooks/Chapter5_NumPyExercise.ipynb" "/content/drive/MyDrive/IS110_BPerformance_Bucago/IS110_repo_Bucago/PythonEnvi_Bucago/"

In [20]:
%cd /content/drive/MyDrive/IS110_BPerformance_Bucago/IS110_repo_Bucago/

/content/drive/MyDrive/IS110_BPerformance_Bucago/IS110_repo_Bucago


In [21]:
!ls PythonEnvi_Bucago/

Chapter3.ipynb	Chapter5.ipynb		      myenv
Chapter4.ipynb	Chapter5_NumPyExercise.ipynb  requirements.txt


In [22]:
!git add .

^C


In [ ]:
!git commit -m "Chapter 5 NumPy Exercise"

^C


In [ ]:
!git push origin main